services:
  db:
    image: postgres:18-alpine
    container_name: sniply_db
    environment:
      POSTGRES_DB: sniply
      POSTGRES_USER: sniply
      POSTGRES_PASSWORD: sniply
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sniply -d sniply"]
      interval: 3s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:v4.19.1
    container_name: sniply_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: ["/migrate", "-source=file:///migrations", "-database=postgres://sniply:sniply@db:5432/sniply?sslmode=disable"]
    command: ["up"]


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sniply_api
    environment:
      APP_PORT: "8080"
      DATABASE_URL: "postgres://sniply:sniply@db:5432/sniply?sslmode=disable"
      JWT_SECRET: "change_me_in_prod_please_use_a_long_random_secret"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started

volumes:
  pgdata:
 